# Generated by Django 2.1.7 on 2019-02-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190215_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='links',
        ),
        migrations.AddField(
            model_name='image',
            name='crawlers',
            field=models.ManyToManyField(blank=True, to='core.Crawler'),
        ),
    ]
