# Generated by Django 2.1.7 on 2019-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190215_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='crawlers',
        ),
        migrations.AddField(
            model_name='crawler',
            name='link',
            field=models.ManyToManyField(blank=True, related_name='_crawler_link_+', to='core.Crawler'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
